packages:
  - .
ignoredBuiltDependencies:
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffprobe-installer/darwin-arm64'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - prisma
  - protobufjs
  - unrs-resolver
